name: Deploy to VPS

on:
  push:
    branches: 
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: rsync -avz --delete -e "ssh" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/cvile/html

    - name: Install dependencies
      run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/cvile && source venv/bin/activate && pip install -r html/requirements.txt"

    - name: Restart Flask App
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          sudo systemctl stop lsws
          sudo pkill -f 'cvile.*wsgi.py' || true
          sudo systemctl start lsws
        "